/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cinema1;

import static java.lang.Integer.parseInt;

/**
 *
 * @author Abdalla
 */

public class ReservationGUI extends javax.swing.JFrame {

    
    
    Acontroller C=new Acontroller();   // new
    
    
    
    //Reservation Reserve=new Reservation();
    //TicketInfo Ticket= new TicketInfo();
    static int count=0;
    
    /**
     * Creates new form NewJFrame
     */
    public ReservationGUI() {
        initComponents();
        count++;
        setLocationRelativeTo(null);
    }
    
    Pay PGUI= new Pay();
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        MovieComboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        ScreenTextField = new javax.swing.JTextField();
        DateComboBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        SeatComboBox = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        ScreenTyTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jButton1.setText("jButton1");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setText("Reservation");

        MovieComboBox.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        MovieComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Movie1", "Movie2", "Movie3", "Movie4", "Movie5", "Movie6" }));
        MovieComboBox.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        MovieComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MovieComboBoxActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Screen number:");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel3.setEnabled(false);

        ScreenTextField.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ScreenTextField.setEnabled(false);
        ScreenTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ScreenTextFieldActionPerformed(evt);
            }
        });

        DateComboBox.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        DateComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "(1/1/2018) 3PM", "(1/1/2018) 5PM", "(1/1/2018) 7PM", "(1/1/2018) 9PM" }));
        DateComboBox.setDoubleBuffered(true);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Choose a movie:");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel4.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Choose a date:");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel5.setEnabled(false);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setText("Payment");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"       A", "    Normal", "    Normal", "    Normal"},
                {"       B", "    VIP", "    VIP", "    VIP"},
                {"       C", "    Normal", "    Normal", "    Normal"},
                {"       D", "    Normal", "    Normal", "    Normal"}
            },
            new String [] {
                "     0", "     1", "     2", "     3"
            }
        ));
        jTable2.setEnabled(false);
        jScrollPane2.setViewportView(jTable2);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 51, 51));
        jLabel6.setText("                  S C R E E N");
        jLabel6.setEnabled(false);

        SeatComboBox.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        SeatComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A-1", "A-2", "A-3", "B-1 (VIP)", "B-2 (VIP)", "B-3 (VIP)", "C-1", "C-2", "C-3", "D-1", "D-2", "D-3" }));
        SeatComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeatComboBoxActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("Choose seat:");
        jLabel7.setEnabled(false);

        ScreenTyTextField.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ScreenTyTextField.setEnabled(false);
        ScreenTyTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ScreenTyTextFieldActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Screen Type:");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel8.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE))))
                .addGap(34, 34, 34))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(247, 247, 247))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(MovieComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ScreenTyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(SeatComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(ScreenTextField)
                                            .addGap(1, 1, 1)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(jLabel2)))
                .addContainerGap(216, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MovieComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ScreenTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ScreenTyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)))
                .addGap(35, 35, 35)
                .addComponent(jLabel6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SeatComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(54, 54, 54)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ScreenTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ScreenTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ScreenTextFieldActionPerformed

    private void MovieComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MovieComboBoxActionPerformed
       
        if (MovieComboBox.getSelectedItem().toString() == "Movie1") {
            ScreenTextField.setText("1");
            ScreenTyTextField.setText("IMAX");
        } else if (MovieComboBox.getSelectedItem().toString() == "Movie2") {
            ScreenTextField.setText("2");
            ScreenTyTextField.setText("IMAX");
        } else if (MovieComboBox.getSelectedItem().toString() == "Movie3") {
            ScreenTextField.setText("3");
            ScreenTyTextField.setText("IMAX");
        } else if (MovieComboBox.getSelectedItem().toString() == "Movie4") {
            ScreenTextField.setText("4");
            ScreenTyTextField.setText("Normal");
        } else if (MovieComboBox.getSelectedItem().toString() == "Movie5") {
            ScreenTextField.setText("5");
            ScreenTyTextField.setText("Normal");
        } else if (MovieComboBox.getSelectedItem().toString() == "Movie6") {
            ScreenTextField.setText("6");
            ScreenTyTextField.setText("Normal");
        }
   
    }//GEN-LAST:event_MovieComboBoxActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        if (SeatComboBox.getSelectedItem().toString().charAt(0) == 'B'
                && (MovieComboBox.getSelectedItem().toString() == "Movie1"
                || MovieComboBox.getSelectedItem().toString() == "Movie2"
                || MovieComboBox.getSelectedItem().toString() == "Movie3")) {
            //  old   Ticket.addTicket(SeatComboBox.getSelectedItem().toString(),count, Integer.parseInt(ScreenTextField.getText().toString()), true, true);
            //  old   Reserve.makeReservation(count,DateComboBox.getSelectedItem().toString());
            
            C.T.addTicket(SeatComboBox.getSelectedItem().toString(),count,100 ,Integer.parseInt(ScreenTextField.getText().toString()), true, true); //new 100
            C.R.makeReservation(count,DateComboBox.getSelectedItem().toString()); //new
            
            this.dispose();
            PGUI.setVisible(true);
        } else if (SeatComboBox.getSelectedItem().toString().charAt(0) != 'B'
                && (MovieComboBox.getSelectedItem().toString() == "Movie1"
                || MovieComboBox.getSelectedItem().toString() == "Movie2"
                || MovieComboBox.getSelectedItem().toString() == "Movie3")) {
            // Ticket.addTicket(SeatComboBox.getSelectedItem().toString(),count, Integer.parseInt(ScreenTextField.getText().toString()), true, false);
            // Reserve.makeReservation(count,DateComboBox.getSelectedItem().toString());
            
            C.T.addTicket(SeatComboBox.getSelectedItem().toString(),count,70, Integer.parseInt(ScreenTextField.getText().toString()), true, false); //new 70
            C.R.makeReservation(count,DateComboBox.getSelectedItem().toString()); //new
            
            
            this.dispose();
            PGUI.setVisible(true);
        } else if (SeatComboBox.getSelectedItem().toString().charAt(0) == 'B'
                && (MovieComboBox.getSelectedItem().toString() != "Movie1"
                || MovieComboBox.getSelectedItem().toString() != "Movie2"
                || MovieComboBox.getSelectedItem().toString() != "Movie3")) {
            //Ticket.addTicket(SeatComboBox.getSelectedItem().toString(),count, Integer.parseInt(ScreenTextField.getText().toString()), false, true); 80
            //Reserve.makeReservation(count,DateComboBox.getSelectedItem().toString());
            
            
            C.T.addTicket(SeatComboBox.getSelectedItem().toString(),count,80, Integer.parseInt(ScreenTextField.getText().toString()), false, true); //new 50
            C.R.makeReservation(count,DateComboBox.getSelectedItem().toString()); //new
            
            this.dispose();
            PGUI.setVisible(true);
        } else {
            //Ticket.addTicket(SeatComboBox.getSelectedItem().toString(),count, Integer.parseInt(ScreenTextField.getText().toString()), false, false);
            //Reserve.makeReservation(count,DateComboBox.getSelectedItem().toString());
            
            C.T.addTicket(SeatComboBox.getSelectedItem().toString(),count,50, Integer.parseInt(ScreenTextField.getText().toString()), false, false); //new
            C.R.makeReservation(count,DateComboBox.getSelectedItem().toString()); //new
            
            
            this.dispose();
            PGUI.setVisible(true);
        }
        
        
        
        

    }//GEN-LAST:event_jButton2ActionPerformed

    private void SeatComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeatComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SeatComboBoxActionPerformed

    private void ScreenTyTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ScreenTyTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ScreenTyTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReservationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReservationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReservationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReservationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReservationGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> DateComboBox;
    private javax.swing.JComboBox<String> MovieComboBox;
    private javax.swing.JTextField ScreenTextField;
    private javax.swing.JTextField ScreenTyTextField;
    private javax.swing.JComboBox<String> SeatComboBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables

    
}
